version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - app-network
  server:
    container_name: node-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    networks:
      - app-network
  mongo:
    container_name: mongo-dotaproplayers
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge